// Code generated by ent, DO NOT EDIT.

package subject

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subject type in the database.
	Label = "subject"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubjectType holds the string denoting the subjecttype field in the database.
	FieldSubjectType = "subject_type"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// EdgeStatement holds the string denoting the statement edge name in mutations.
	EdgeStatement = "statement"
	// Table holds the table name of the subject in the database.
	Table = "subjects"
	// StatementTable is the table that holds the statement relation/edge. The primary key declared below.
	StatementTable = "statement_subjects"
	// StatementInverseTable is the table name for the Statement entity.
	// It exists in this package in order to avoid circular dependency with the "statement" package.
	StatementInverseTable = "statements"
)

// Columns holds all SQL columns for subject fields.
var Columns = []string{
	FieldID,
	FieldSubjectType,
	FieldSubject,
}

var (
	// StatementPrimaryKey and StatementColumn2 are the table columns denoting the
	// primary key for the statement relation (M2M).
	StatementPrimaryKey = []string{"statement_id", "subject_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Subject queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubjectType orders the results by the subjectType field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// ByStatementCount orders the results by statement count.
func ByStatementCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatementStep(), opts...)
	}
}

// ByStatement orders the results by statement terms.
func ByStatement(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatementStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStatementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, StatementTable, StatementPrimaryKey...),
	)
}
