// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StatementIndexesColumns holds the columns for the "statement_indexes" table.
	StatementIndexesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "object", Type: field.TypeJSON},
		{Name: "predicate", Type: field.TypeJSON},
		{Name: "subject", Type: field.TypeJSON},
		{Name: "statement", Type: field.TypeJSON},
	}
	// StatementIndexesTable holds the schema information for the "statement_indexes" table.
	StatementIndexesTable = &schema.Table{
		Name:       "statement_indexes",
		Columns:    StatementIndexesColumns,
		PrimaryKey: []*schema.Column{StatementIndexesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StatementIndexesTable,
	}
)

func init() {
}
