// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/spredicate"
	"zotregistry.io/zot/ent/statement"
)

// SpredicateQuery is the builder for querying Spredicate entities.
type SpredicateQuery struct {
	config
	ctx                *QueryContext
	order              []spredicate.OrderOption
	inters             []Interceptor
	predicates         []predicate.Spredicate
	withStatement      *StatementQuery
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Spredicate) error
	withNamedStatement map[string]*StatementQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpredicateQuery builder.
func (sq *SpredicateQuery) Where(ps ...predicate.Spredicate) *SpredicateQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SpredicateQuery) Limit(limit int) *SpredicateQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SpredicateQuery) Offset(offset int) *SpredicateQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SpredicateQuery) Unique(unique bool) *SpredicateQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SpredicateQuery) Order(o ...spredicate.OrderOption) *SpredicateQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryStatement chains the current query on the "statement" edge.
func (sq *SpredicateQuery) QueryStatement() *StatementQuery {
	query := (&StatementClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spredicate.Table, spredicate.FieldID, selector),
			sqlgraph.To(statement.Table, statement.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, spredicate.StatementTable, spredicate.StatementPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Spredicate entity from the query.
// Returns a *NotFoundError when no Spredicate was found.
func (sq *SpredicateQuery) First(ctx context.Context) (*Spredicate, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{spredicate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SpredicateQuery) FirstX(ctx context.Context) *Spredicate {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Spredicate ID from the query.
// Returns a *NotFoundError when no Spredicate ID was found.
func (sq *SpredicateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{spredicate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SpredicateQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Spredicate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Spredicate entity is found.
// Returns a *NotFoundError when no Spredicate entities are found.
func (sq *SpredicateQuery) Only(ctx context.Context) (*Spredicate, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{spredicate.Label}
	default:
		return nil, &NotSingularError{spredicate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SpredicateQuery) OnlyX(ctx context.Context) *Spredicate {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Spredicate ID in the query.
// Returns a *NotSingularError when more than one Spredicate ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SpredicateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{spredicate.Label}
	default:
		err = &NotSingularError{spredicate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SpredicateQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Spredicates.
func (sq *SpredicateQuery) All(ctx context.Context) ([]*Spredicate, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Spredicate, *SpredicateQuery]()
	return withInterceptors[[]*Spredicate](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SpredicateQuery) AllX(ctx context.Context) []*Spredicate {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Spredicate IDs.
func (sq *SpredicateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(spredicate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SpredicateQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SpredicateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SpredicateQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SpredicateQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SpredicateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SpredicateQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpredicateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SpredicateQuery) Clone() *SpredicateQuery {
	if sq == nil {
		return nil
	}
	return &SpredicateQuery{
		config:        sq.config,
		ctx:           sq.ctx.Clone(),
		order:         append([]spredicate.OrderOption{}, sq.order...),
		inters:        append([]Interceptor{}, sq.inters...),
		predicates:    append([]predicate.Spredicate{}, sq.predicates...),
		withStatement: sq.withStatement.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithStatement tells the query-builder to eager-load the nodes that are connected to
// the "statement" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SpredicateQuery) WithStatement(opts ...func(*StatementQuery)) *SpredicateQuery {
	query := (&StatementClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withStatement = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PredicateType string `json:"predicateType,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Spredicate.Query().
//		GroupBy(spredicate.FieldPredicateType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SpredicateQuery) GroupBy(field string, fields ...string) *SpredicateGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SpredicateGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = spredicate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PredicateType string `json:"predicateType,omitempty"`
//	}
//
//	client.Spredicate.Query().
//		Select(spredicate.FieldPredicateType).
//		Scan(ctx, &v)
func (sq *SpredicateQuery) Select(fields ...string) *SpredicateSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SpredicateSelect{SpredicateQuery: sq}
	sbuild.label = spredicate.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SpredicateSelect configured with the given aggregations.
func (sq *SpredicateQuery) Aggregate(fns ...AggregateFunc) *SpredicateSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SpredicateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !spredicate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SpredicateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Spredicate, error) {
	var (
		nodes       = []*Spredicate{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withStatement != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Spredicate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Spredicate{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withStatement; query != nil {
		if err := sq.loadStatement(ctx, query, nodes,
			func(n *Spredicate) { n.Edges.Statement = []*Statement{} },
			func(n *Spredicate, e *Statement) { n.Edges.Statement = append(n.Edges.Statement, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range sq.withNamedStatement {
		if err := sq.loadStatement(ctx, query, nodes,
			func(n *Spredicate) { n.appendNamedStatement(name) },
			func(n *Spredicate, e *Statement) { n.appendNamedStatement(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range sq.loadTotal {
		if err := sq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SpredicateQuery) loadStatement(ctx context.Context, query *StatementQuery, nodes []*Spredicate, init func(*Spredicate), assign func(*Spredicate, *Statement)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Spredicate)
	nids := make(map[int]map[*Spredicate]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(spredicate.StatementTable)
		s.Join(joinT).On(s.C(statement.FieldID), joinT.C(spredicate.StatementPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(spredicate.StatementPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(spredicate.StatementPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Spredicate]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Statement](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "statement" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (sq *SpredicateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SpredicateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(spredicate.Table, spredicate.Columns, sqlgraph.NewFieldSpec(spredicate.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spredicate.FieldID)
		for i := range fields {
			if fields[i] != spredicate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SpredicateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(spredicate.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = spredicate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedStatement tells the query-builder to eager-load the nodes that are connected to the "statement"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (sq *SpredicateQuery) WithNamedStatement(name string, opts ...func(*StatementQuery)) *SpredicateQuery {
	query := (&StatementClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if sq.withNamedStatement == nil {
		sq.withNamedStatement = make(map[string]*StatementQuery)
	}
	sq.withNamedStatement[name] = query
	return sq
}

// SpredicateGroupBy is the group-by builder for Spredicate entities.
type SpredicateGroupBy struct {
	selector
	build *SpredicateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SpredicateGroupBy) Aggregate(fns ...AggregateFunc) *SpredicateGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SpredicateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpredicateQuery, *SpredicateGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SpredicateGroupBy) sqlScan(ctx context.Context, root *SpredicateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SpredicateSelect is the builder for selecting fields of Spredicate entities.
type SpredicateSelect struct {
	*SpredicateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SpredicateSelect) Aggregate(fns ...AggregateFunc) *SpredicateSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SpredicateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpredicateQuery, *SpredicateSelect](ctx, ss.SpredicateQuery, ss, ss.inters, v)
}

func (ss *SpredicateSelect) sqlScan(ctx context.Context, root *SpredicateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
