// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/spredicate"
	"zotregistry.io/zot/ent/statement"
)

// SpredicateCreate is the builder for creating a Spredicate entity.
type SpredicateCreate struct {
	config
	mutation *SpredicateMutation
	hooks    []Hook
}

// SetPredicateType sets the "predicateType" field.
func (sc *SpredicateCreate) SetPredicateType(s string) *SpredicateCreate {
	sc.mutation.SetPredicateType(s)
	return sc
}

// SetPredicate sets the "predicate" field.
func (sc *SpredicateCreate) SetPredicate(m map[string]interface{}) *SpredicateCreate {
	sc.mutation.SetPredicate(m)
	return sc
}

// AddStatementIDs adds the "statement" edge to the Statement entity by IDs.
func (sc *SpredicateCreate) AddStatementIDs(ids ...int) *SpredicateCreate {
	sc.mutation.AddStatementIDs(ids...)
	return sc
}

// AddStatement adds the "statement" edges to the Statement entity.
func (sc *SpredicateCreate) AddStatement(s ...*Statement) *SpredicateCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddStatementIDs(ids...)
}

// Mutation returns the SpredicateMutation object of the builder.
func (sc *SpredicateCreate) Mutation() *SpredicateMutation {
	return sc.mutation
}

// Save creates the Spredicate in the database.
func (sc *SpredicateCreate) Save(ctx context.Context) (*Spredicate, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SpredicateCreate) SaveX(ctx context.Context) *Spredicate {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SpredicateCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SpredicateCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SpredicateCreate) check() error {
	if _, ok := sc.mutation.PredicateType(); !ok {
		return &ValidationError{Name: "predicateType", err: errors.New(`ent: missing required field "Spredicate.predicateType"`)}
	}
	if _, ok := sc.mutation.Predicate(); !ok {
		return &ValidationError{Name: "predicate", err: errors.New(`ent: missing required field "Spredicate.predicate"`)}
	}
	return nil
}

func (sc *SpredicateCreate) sqlSave(ctx context.Context) (*Spredicate, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SpredicateCreate) createSpec() (*Spredicate, *sqlgraph.CreateSpec) {
	var (
		_node = &Spredicate{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(spredicate.Table, sqlgraph.NewFieldSpec(spredicate.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.PredicateType(); ok {
		_spec.SetField(spredicate.FieldPredicateType, field.TypeString, value)
		_node.PredicateType = value
	}
	if value, ok := sc.mutation.Predicate(); ok {
		_spec.SetField(spredicate.FieldPredicate, field.TypeJSON, value)
		_node.Predicate = value
	}
	if nodes := sc.mutation.StatementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SpredicateCreateBulk is the builder for creating many Spredicate entities in bulk.
type SpredicateCreateBulk struct {
	config
	builders []*SpredicateCreate
}

// Save creates the Spredicate entities in the database.
func (scb *SpredicateCreateBulk) Save(ctx context.Context) ([]*Spredicate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Spredicate, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpredicateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SpredicateCreateBulk) SaveX(ctx context.Context) []*Spredicate {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SpredicateCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SpredicateCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
