// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/spredicate"
	"zotregistry.io/zot/ent/statement"
)

// SpredicateUpdate is the builder for updating Spredicate entities.
type SpredicateUpdate struct {
	config
	hooks    []Hook
	mutation *SpredicateMutation
}

// Where appends a list predicates to the SpredicateUpdate builder.
func (su *SpredicateUpdate) Where(ps ...predicate.Spredicate) *SpredicateUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetPredicateType sets the "predicateType" field.
func (su *SpredicateUpdate) SetPredicateType(s string) *SpredicateUpdate {
	su.mutation.SetPredicateType(s)
	return su
}

// SetPredicate sets the "predicate" field.
func (su *SpredicateUpdate) SetPredicate(m map[string]interface{}) *SpredicateUpdate {
	su.mutation.SetPredicate(m)
	return su
}

// AddStatementIDs adds the "statement" edge to the Statement entity by IDs.
func (su *SpredicateUpdate) AddStatementIDs(ids ...int) *SpredicateUpdate {
	su.mutation.AddStatementIDs(ids...)
	return su
}

// AddStatement adds the "statement" edges to the Statement entity.
func (su *SpredicateUpdate) AddStatement(s ...*Statement) *SpredicateUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddStatementIDs(ids...)
}

// Mutation returns the SpredicateMutation object of the builder.
func (su *SpredicateUpdate) Mutation() *SpredicateMutation {
	return su.mutation
}

// ClearStatement clears all "statement" edges to the Statement entity.
func (su *SpredicateUpdate) ClearStatement() *SpredicateUpdate {
	su.mutation.ClearStatement()
	return su
}

// RemoveStatementIDs removes the "statement" edge to Statement entities by IDs.
func (su *SpredicateUpdate) RemoveStatementIDs(ids ...int) *SpredicateUpdate {
	su.mutation.RemoveStatementIDs(ids...)
	return su
}

// RemoveStatement removes "statement" edges to Statement entities.
func (su *SpredicateUpdate) RemoveStatement(s ...*Statement) *SpredicateUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveStatementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpredicateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpredicateUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpredicateUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpredicateUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SpredicateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(spredicate.Table, spredicate.Columns, sqlgraph.NewFieldSpec(spredicate.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.PredicateType(); ok {
		_spec.SetField(spredicate.FieldPredicateType, field.TypeString, value)
	}
	if value, ok := su.mutation.Predicate(); ok {
		_spec.SetField(spredicate.FieldPredicate, field.TypeJSON, value)
	}
	if su.mutation.StatementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedStatementIDs(); len(nodes) > 0 && !su.mutation.StatementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.StatementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spredicate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SpredicateUpdateOne is the builder for updating a single Spredicate entity.
type SpredicateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpredicateMutation
}

// SetPredicateType sets the "predicateType" field.
func (suo *SpredicateUpdateOne) SetPredicateType(s string) *SpredicateUpdateOne {
	suo.mutation.SetPredicateType(s)
	return suo
}

// SetPredicate sets the "predicate" field.
func (suo *SpredicateUpdateOne) SetPredicate(m map[string]interface{}) *SpredicateUpdateOne {
	suo.mutation.SetPredicate(m)
	return suo
}

// AddStatementIDs adds the "statement" edge to the Statement entity by IDs.
func (suo *SpredicateUpdateOne) AddStatementIDs(ids ...int) *SpredicateUpdateOne {
	suo.mutation.AddStatementIDs(ids...)
	return suo
}

// AddStatement adds the "statement" edges to the Statement entity.
func (suo *SpredicateUpdateOne) AddStatement(s ...*Statement) *SpredicateUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddStatementIDs(ids...)
}

// Mutation returns the SpredicateMutation object of the builder.
func (suo *SpredicateUpdateOne) Mutation() *SpredicateMutation {
	return suo.mutation
}

// ClearStatement clears all "statement" edges to the Statement entity.
func (suo *SpredicateUpdateOne) ClearStatement() *SpredicateUpdateOne {
	suo.mutation.ClearStatement()
	return suo
}

// RemoveStatementIDs removes the "statement" edge to Statement entities by IDs.
func (suo *SpredicateUpdateOne) RemoveStatementIDs(ids ...int) *SpredicateUpdateOne {
	suo.mutation.RemoveStatementIDs(ids...)
	return suo
}

// RemoveStatement removes "statement" edges to Statement entities.
func (suo *SpredicateUpdateOne) RemoveStatement(s ...*Statement) *SpredicateUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveStatementIDs(ids...)
}

// Where appends a list predicates to the SpredicateUpdate builder.
func (suo *SpredicateUpdateOne) Where(ps ...predicate.Spredicate) *SpredicateUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpredicateUpdateOne) Select(field string, fields ...string) *SpredicateUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Spredicate entity.
func (suo *SpredicateUpdateOne) Save(ctx context.Context) (*Spredicate, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpredicateUpdateOne) SaveX(ctx context.Context) *Spredicate {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpredicateUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpredicateUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SpredicateUpdateOne) sqlSave(ctx context.Context) (_node *Spredicate, err error) {
	_spec := sqlgraph.NewUpdateSpec(spredicate.Table, spredicate.Columns, sqlgraph.NewFieldSpec(spredicate.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Spredicate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spredicate.FieldID)
		for _, f := range fields {
			if !spredicate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != spredicate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.PredicateType(); ok {
		_spec.SetField(spredicate.FieldPredicateType, field.TypeString, value)
	}
	if value, ok := suo.mutation.Predicate(); ok {
		_spec.SetField(spredicate.FieldPredicate, field.TypeJSON, value)
	}
	if suo.mutation.StatementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedStatementIDs(); len(nodes) > 0 && !suo.mutation.StatementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.StatementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   spredicate.StatementTable,
			Columns: spredicate.StatementPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Spredicate{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spredicate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
