// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/statementindex"
)

// StatementIndexDelete is the builder for deleting a StatementIndex entity.
type StatementIndexDelete struct {
	config
	hooks    []Hook
	mutation *StatementIndexMutation
}

// Where appends a list predicates to the StatementIndexDelete builder.
func (sid *StatementIndexDelete) Where(ps ...predicate.StatementIndex) *StatementIndexDelete {
	sid.mutation.Where(ps...)
	return sid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sid *StatementIndexDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sid.sqlExec, sid.mutation, sid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sid *StatementIndexDelete) ExecX(ctx context.Context) int {
	n, err := sid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sid *StatementIndexDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(statementindex.Table, sqlgraph.NewFieldSpec(statementindex.FieldID, field.TypeInt))
	if ps := sid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sid.mutation.done = true
	return affected, err
}

// StatementIndexDeleteOne is the builder for deleting a single StatementIndex entity.
type StatementIndexDeleteOne struct {
	sid *StatementIndexDelete
}

// Where appends a list predicates to the StatementIndexDelete builder.
func (sido *StatementIndexDeleteOne) Where(ps ...predicate.StatementIndex) *StatementIndexDeleteOne {
	sido.sid.mutation.Where(ps...)
	return sido
}

// Exec executes the deletion query.
func (sido *StatementIndexDeleteOne) Exec(ctx context.Context) error {
	n, err := sido.sid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{statementindex.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sido *StatementIndexDeleteOne) ExecX(ctx context.Context) {
	if err := sido.Exec(ctx); err != nil {
		panic(err)
	}
}
