// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zotregistry.io/zot/ent/predicate"
	"zotregistry.io/zot/ent/statementindex"
)

// StatementIndexQuery is the builder for querying StatementIndex entities.
type StatementIndexQuery struct {
	config
	ctx        *QueryContext
	order      []statementindex.OrderOption
	inters     []Interceptor
	predicates []predicate.StatementIndex
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StatementIndexQuery builder.
func (siq *StatementIndexQuery) Where(ps ...predicate.StatementIndex) *StatementIndexQuery {
	siq.predicates = append(siq.predicates, ps...)
	return siq
}

// Limit the number of records to be returned by this query.
func (siq *StatementIndexQuery) Limit(limit int) *StatementIndexQuery {
	siq.ctx.Limit = &limit
	return siq
}

// Offset to start from.
func (siq *StatementIndexQuery) Offset(offset int) *StatementIndexQuery {
	siq.ctx.Offset = &offset
	return siq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (siq *StatementIndexQuery) Unique(unique bool) *StatementIndexQuery {
	siq.ctx.Unique = &unique
	return siq
}

// Order specifies how the records should be ordered.
func (siq *StatementIndexQuery) Order(o ...statementindex.OrderOption) *StatementIndexQuery {
	siq.order = append(siq.order, o...)
	return siq
}

// First returns the first StatementIndex entity from the query.
// Returns a *NotFoundError when no StatementIndex was found.
func (siq *StatementIndexQuery) First(ctx context.Context) (*StatementIndex, error) {
	nodes, err := siq.Limit(1).All(setContextOp(ctx, siq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{statementindex.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (siq *StatementIndexQuery) FirstX(ctx context.Context) *StatementIndex {
	node, err := siq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StatementIndex ID from the query.
// Returns a *NotFoundError when no StatementIndex ID was found.
func (siq *StatementIndexQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = siq.Limit(1).IDs(setContextOp(ctx, siq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{statementindex.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (siq *StatementIndexQuery) FirstIDX(ctx context.Context) int {
	id, err := siq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StatementIndex entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StatementIndex entity is found.
// Returns a *NotFoundError when no StatementIndex entities are found.
func (siq *StatementIndexQuery) Only(ctx context.Context) (*StatementIndex, error) {
	nodes, err := siq.Limit(2).All(setContextOp(ctx, siq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{statementindex.Label}
	default:
		return nil, &NotSingularError{statementindex.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (siq *StatementIndexQuery) OnlyX(ctx context.Context) *StatementIndex {
	node, err := siq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StatementIndex ID in the query.
// Returns a *NotSingularError when more than one StatementIndex ID is found.
// Returns a *NotFoundError when no entities are found.
func (siq *StatementIndexQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = siq.Limit(2).IDs(setContextOp(ctx, siq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{statementindex.Label}
	default:
		err = &NotSingularError{statementindex.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (siq *StatementIndexQuery) OnlyIDX(ctx context.Context) int {
	id, err := siq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StatementIndexes.
func (siq *StatementIndexQuery) All(ctx context.Context) ([]*StatementIndex, error) {
	ctx = setContextOp(ctx, siq.ctx, "All")
	if err := siq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StatementIndex, *StatementIndexQuery]()
	return withInterceptors[[]*StatementIndex](ctx, siq, qr, siq.inters)
}

// AllX is like All, but panics if an error occurs.
func (siq *StatementIndexQuery) AllX(ctx context.Context) []*StatementIndex {
	nodes, err := siq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StatementIndex IDs.
func (siq *StatementIndexQuery) IDs(ctx context.Context) (ids []int, err error) {
	if siq.ctx.Unique == nil && siq.path != nil {
		siq.Unique(true)
	}
	ctx = setContextOp(ctx, siq.ctx, "IDs")
	if err = siq.Select(statementindex.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (siq *StatementIndexQuery) IDsX(ctx context.Context) []int {
	ids, err := siq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (siq *StatementIndexQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, siq.ctx, "Count")
	if err := siq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, siq, querierCount[*StatementIndexQuery](), siq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (siq *StatementIndexQuery) CountX(ctx context.Context) int {
	count, err := siq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (siq *StatementIndexQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, siq.ctx, "Exist")
	switch _, err := siq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (siq *StatementIndexQuery) ExistX(ctx context.Context) bool {
	exist, err := siq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StatementIndexQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (siq *StatementIndexQuery) Clone() *StatementIndexQuery {
	if siq == nil {
		return nil
	}
	return &StatementIndexQuery{
		config:     siq.config,
		ctx:        siq.ctx.Clone(),
		order:      append([]statementindex.OrderOption{}, siq.order...),
		inters:     append([]Interceptor{}, siq.inters...),
		predicates: append([]predicate.StatementIndex{}, siq.predicates...),
		// clone intermediate query.
		sql:  siq.sql.Clone(),
		path: siq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Object schema.Object `json:"object,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StatementIndex.Query().
//		GroupBy(statementindex.FieldObject).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (siq *StatementIndexQuery) GroupBy(field string, fields ...string) *StatementIndexGroupBy {
	siq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StatementIndexGroupBy{build: siq}
	grbuild.flds = &siq.ctx.Fields
	grbuild.label = statementindex.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Object schema.Object `json:"object,omitempty"`
//	}
//
//	client.StatementIndex.Query().
//		Select(statementindex.FieldObject).
//		Scan(ctx, &v)
func (siq *StatementIndexQuery) Select(fields ...string) *StatementIndexSelect {
	siq.ctx.Fields = append(siq.ctx.Fields, fields...)
	sbuild := &StatementIndexSelect{StatementIndexQuery: siq}
	sbuild.label = statementindex.Label
	sbuild.flds, sbuild.scan = &siq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StatementIndexSelect configured with the given aggregations.
func (siq *StatementIndexQuery) Aggregate(fns ...AggregateFunc) *StatementIndexSelect {
	return siq.Select().Aggregate(fns...)
}

func (siq *StatementIndexQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range siq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, siq); err != nil {
				return err
			}
		}
	}
	for _, f := range siq.ctx.Fields {
		if !statementindex.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if siq.path != nil {
		prev, err := siq.path(ctx)
		if err != nil {
			return err
		}
		siq.sql = prev
	}
	return nil
}

func (siq *StatementIndexQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StatementIndex, error) {
	var (
		nodes = []*StatementIndex{}
		_spec = siq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StatementIndex).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StatementIndex{config: siq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, siq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (siq *StatementIndexQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := siq.querySpec()
	_spec.Node.Columns = siq.ctx.Fields
	if len(siq.ctx.Fields) > 0 {
		_spec.Unique = siq.ctx.Unique != nil && *siq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, siq.driver, _spec)
}

func (siq *StatementIndexQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(statementindex.Table, statementindex.Columns, sqlgraph.NewFieldSpec(statementindex.FieldID, field.TypeInt))
	_spec.From = siq.sql
	if unique := siq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if siq.path != nil {
		_spec.Unique = true
	}
	if fields := siq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statementindex.FieldID)
		for i := range fields {
			if fields[i] != statementindex.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := siq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := siq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := siq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := siq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (siq *StatementIndexQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(siq.driver.Dialect())
	t1 := builder.Table(statementindex.Table)
	columns := siq.ctx.Fields
	if len(columns) == 0 {
		columns = statementindex.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if siq.sql != nil {
		selector = siq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if siq.ctx.Unique != nil && *siq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range siq.predicates {
		p(selector)
	}
	for _, p := range siq.order {
		p(selector)
	}
	if offset := siq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := siq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StatementIndexGroupBy is the group-by builder for StatementIndex entities.
type StatementIndexGroupBy struct {
	selector
	build *StatementIndexQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sigb *StatementIndexGroupBy) Aggregate(fns ...AggregateFunc) *StatementIndexGroupBy {
	sigb.fns = append(sigb.fns, fns...)
	return sigb
}

// Scan applies the selector query and scans the result into the given value.
func (sigb *StatementIndexGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sigb.build.ctx, "GroupBy")
	if err := sigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StatementIndexQuery, *StatementIndexGroupBy](ctx, sigb.build, sigb, sigb.build.inters, v)
}

func (sigb *StatementIndexGroupBy) sqlScan(ctx context.Context, root *StatementIndexQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sigb.fns))
	for _, fn := range sigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sigb.flds)+len(sigb.fns))
		for _, f := range *sigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StatementIndexSelect is the builder for selecting fields of StatementIndex entities.
type StatementIndexSelect struct {
	*StatementIndexQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sis *StatementIndexSelect) Aggregate(fns ...AggregateFunc) *StatementIndexSelect {
	sis.fns = append(sis.fns, fns...)
	return sis
}

// Scan applies the selector query and scans the result into the given value.
func (sis *StatementIndexSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sis.ctx, "Select")
	if err := sis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StatementIndexQuery, *StatementIndexSelect](ctx, sis.StatementIndexQuery, sis, sis.inters, v)
}

func (sis *StatementIndexSelect) sqlScan(ctx context.Context, root *StatementIndexQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sis.fns))
	for _, fn := range sis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
