// Code generated by ent, DO NOT EDIT.

package statementindex

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the statementindex type in the database.
	Label = "statement_index"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldObject holds the string denoting the object field in the database.
	FieldObject = "object"
	// FieldPredicate holds the string denoting the predicate field in the database.
	FieldPredicate = "predicate"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldStatement holds the string denoting the statement field in the database.
	FieldStatement = "statement"
	// Table holds the table name of the statementindex in the database.
	Table = "statement_indexes"
)

// Columns holds all SQL columns for statementindex fields.
var Columns = []string{
	FieldID,
	FieldObject,
	FieldPredicate,
	FieldSubject,
	FieldStatement,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the StatementIndex queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
