// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StatementIndex is the predicate function for statementindex builders.
type StatementIndex func(*sql.Selector)
