// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// Spredicate is the predicate function for spredicate builders.
type Spredicate func(*sql.Selector)

// Statement is the predicate function for statement builders.
type Statement func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)
